[project]
name = "enczoo"
version = "0.1.5.dev3"
description = "Easily map images (as `PIL.Images`) to features (as `np.ndarray`) from pretrained vision models."
readme = "README.md"
authors = [
    { name = "Michael J. Lee", email = "mil@mit.edu" }
]
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "ftfy>=6.3.1",
    "pillow>=12.1.0",
    "tensorflow>=2.21.0; sys_platform == 'darwin'",
    "tensorflow[and-cuda]>=2.21.0; sys_platform == 'linux' or sys_platform == 'win32'",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
    "transformers>=5.3.0",
]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=25.12.0",
    "matplotlib>=3.10.8",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "ty>=0.0.9",
]

[tool.ty.src]
exclude = ["src/enczoo/_vendor/"]

[tool.ruff]
exclude = ["src/enczoo/_vendor"]
