[build-system]
requires = ["setuptools>=42", "wheel"]  # Add build dependencies
build-backend = "setuptools.build_meta"

[project]
name = "enczoo"
version = "0.0.5"
description = "A zoo of encoding models"
authors = [
    { name = "Michael J. Lee", email = "mil@mit.edu" }
]
license = { file = "license.md" }
readme = "README.md"
requires-python = ">=3.11"

# Dependencies from requirements.txt
dependencies = [
    "pytest>=8.3",
    "pillow>=10.4",
    "pydantic>=2.10",
    "torch>=2.2",
    "torchvision>=0.19",
    "tensorbucket @ git+https://github.com/himjl/tensorbucket.git",
    "mref @ git+https://github.com/himjl/mref.git",
]

[project.urls]
repository = "https://github.com/himjl/enczoo"

[tool.setuptools.packages.find]
where = ["."]
namespaces = false
