name: CI

on:
  push:
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - .github/workflows/ci.yml
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Create venv
        run: uv venv
      - name: Install package
        run: uv pip install -e .
      - name: Run pytests
        run: uv run pytest -s
